# Generated by Django 4.2.7 on 2023-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_registration",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
    ]
