# Generated by Django 4.2.7 on 2023-11-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_user_registration_isverified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
