# Generated by Django 4.2.7 on 2023-11-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_alter_user_registration_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
