# Generated by Django 4.2.7 on 2023-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_alter_user_registration_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="acceptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.PositiveIntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("hospital_name", models.CharField(max_length=255)),
                ("hospital_address", models.CharField(max_length=255)),
                ("emergency", models.CharField(blank=True, max_length=255, null=True)),
                ("blood_group", models.CharField(max_length=16)),
                ("blood_type", models.CharField(max_length=27)),
                ("required_by", models.DateField()),
                ("agree", models.BooleanField()),
            ],
        ),
    ]
