# Generated by Django 4.2.7 on 2023-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_acceptor"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptor",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acceptor",
            name="mobile",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
