# Generated by Django 4.2.7 on 2023-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_acceptor_email_acceptor_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptor",
            name="units",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
