# Generated by Django 4.2.7 on 2023-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_acceptor_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.PositiveIntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("mobile", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("blood_group", models.CharField(max_length=16)),
                ("health_status", models.CharField(max_length=20)),
                ("last_donated", models.DateField()),
                ("agree", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="acceptor", name="mobile", field=models.CharField(max_length=13),
        ),
    ]
